apiVersion: batch/v1
kind: Job
metadata:
  namespace: demo-namespace
  name: api-privite
spec:
  template:
    spec:
      containers:
        - name: api-privite
          image: registry.cn-shenzhen.aliyuncs.com/ymzy/ymzy-api:1.1.11
          command: ["/bin/sh","-c","ls /etc/config"]
          volumeMounts:
            - mountPath: /etc/config
              name: secret-volume
              readOnly: true
      restartPolicy: Never
      imagePullSecrets:
        - name: registrykey
      volumes:
        - name: secret-volume
          secret:
            secretName: prod-db-secret
  backoffLimit: 4