kind: LimitRange
apiVersion: v1
metadata:
  name: mylimitrange
  namespace: limit-example
spec:
  limits:
    - type: Pod
      max:
        cpu: 4
        memory: 2Gi
      min:
        cpu: 0.2
        memory: 6Mi
      maxLimitRequestRatio: # 限制pod的最大最小内存占用比例
        cpu: 3
        memory: 2

    - type: Container
      default:
        cpu: 0.2
        memory: 200Mi
      min:
        cpu: 0.2
        memory: 200Mi
      max:
        cpu: 0.4
        memory: 400Mi

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq
  namespace: limit-example
spec:
  hard:
    configmaps: 10
    persistentvolumeclaims: 4
    replicationcontrollers: 20
    secrets: 10
    services: 10
    services.loadbalancers: 2
    services.nodeports: 0

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq2
  namespace: limit-example
spec:
  hard:
    pods: 4
  scopes:
    - BestEffort
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq3
  namespace: limit-example
spec:
  hard:
    pods: 4
    requests.cpu: 1
    requests.memory: 800Mi
    limits.cpu: 2
    limits.memory: 1Gi
  scopes:
    - NotBestEffort