#  做了资源限制了有三个状态
#    * Guanteed Pod里的没有容器都有资源限制(内存和CPU)而且必须相同
#    * Burstable Pod里的容器有内存或cpu限制，而且必须相同
#    * BestEffect 其他
#  当宿主机上的资源不足的时候会从下往上顺序驱逐Pod

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-resource
  namespace: demo-namespace
spec:
  selector:
    matchLabels:
      app: nginx-resource
  template:
    metadata:
      name: nginx-resource
      namespace: demo-namespace
      labels:
        app: nginx-resource
    spec:
      containers:
        - name: nginx-resource
          image: nginx
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
              ephemeral-storage: 2Gi # 临时存储单位byte
            limits:
              cpu: 200m
              memory: 200Mi
              ephemeral-storage: 4Gi
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-resouce-service
  namespace: demo-namespace
spec:
  type: NodePort
  selector:
    app: nginx-resource
  ports:
    - port: 80
      nodePort: 32339

