# 通过环境注入的方式将pod的状态等信息注入到容器内部,想要的信息可以在kubectl get pod pod-name -o yaml 的方式查看
# 常常与initcontainer配合实现服务发现
apiVersion: v1
kind: Pod
metadata:
  name: downward-api
  namespace: demo-namespace
  labels:
    zone: us-est-clusterl
  annotations:
    build: two
spec:
  restartPolicy: Never
  volumes:
    - name: pod-info
      downwardAPI:
        items:
          - path: labels
            fieldRef:
              fieldPath: metadata.labels
          - path: annotations
            fieldRef:
              fieldPath: metadata.annotations
  initContainers:
    - name: busybox-downward-api # 挂载为环境变量
      image: busybox
      command: ["/bin/sh","-c","env"]
      env:
        - name: POD_NAME # 获取pod名字
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE # 获取pod的namespace
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: REQUEST_RESOURCE_CPU
          valueFrom:
            resourceFieldRef:
              resource: requests.cpu
        - name: LIMIT_RESOURCE_MEMORY
          valueFrom:
            resourceFieldRef:
              resource:  limits.memory
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP

  containers:  # 挂载为文件
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /etc/k8s
          name: pod-info
          readOnly: true
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 200m
          memory: 200Mi
      livenessProbe:
        tcpSocket: # socket 查看端口是否可用
          port: 80
        httpGet: # http请求查看，200-400 表示正常
          port: /
        exec:
          command:
            - cat
            - tmp/health
        initialDelaySeconds: 30 # 容器启动后首次检查时间
        timeoutSeconds: 1 # 响应超时时间