apiVersion: batch/v1
kind: Job
metadata:
  namespace: demo-namespace
  name: configmap-use-2
  annotations:
    config: config2
spec:
  template:
    spec:
      containers:
        - name: hollow-2
          image: busybox
          command: ["sleep","3600"]
          volumeMounts:
            - mountPath: /etc/config
              name: config-volume
      volumes:
        - name: config-volume
          configMap:
            name: kube-flannel-cfg
      restartPolicy: Never