apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jenkins-jnlp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: managed-nfs-storage

#---
#kind: Pod
#apiVersion: v1
#metadata:
#  name: volume-pv-test
#spec:
#  containers:
#    - name: myfrontend
#      image: nginx
#      volumeMounts:
#        - mountPath: "/usr/share/nginx/html"
#          name: mypd
#  volumes:
#    - name: mypd
#      persistentVolumeClaim:
#        claimName: pvc-jenkins-jnlp