apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test
  namespace: demo-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-volume

---
kind: Pod
apiVersion: v1
metadata:
  name: volume-pv-test
  namespace: demo-namespace
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: pvc-test