# 多个pod之间共享存储
apiVersion: v1
kind: Pod
metadata:
  name: volume-test
#  namespace: demo-namespace
  labels:
    app: volume-test
    istio-injection: enabled
spec:
  volumes:
    - name: volume
      emptyDir: {}
  containers:
    - name: nginx-1
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: volume
  initContainers:
    - name: debian-container
      image: debian
      command:
        - /bin/bash
      args: ["-c", "echo From Shared Data >  /root/volume3/index.html"]
      volumeMounts:
        - mountPath: /root/volume3
          name: volume
---
#apiVersion: apps/v1
#kind: ReplicaSet
#metadata:
#  name: volume-test
#  labels:
#    app: volume-test
#spec:
#  template:
#    metadata:
#      name: volume-test
#      labels:
#        app: volume-test
#    spec:
#      volumes:
#        - name: volume
#          emptyDir: {}
#      containers:
#        - name: nginx-1
#          image: nginx
#          volumeMounts:
#            - mountPath: /usr/share/nginx/html
#              name: volume
#      initContainers:
#        - name: debian-container
#          image: debian
#          command:
#            - /bin/bash
#          args: ["-c", "echo From Shared Data >  /root/volume3/index.html"]
#          volumeMounts:
#            - mountPath: /root/volume3
#              name: volume
#  selector:
#    matchLabels:
#      app: volume-test
#---
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: volume-test
#  labels:
#    app: volume-test
#spec:
#  selector:
#    matchLabels:
#      app: volume-test
#  template:
#    metadata:
#      name: volume-test
#      labels:
#        app: volume-test
#    spec:
#      volumes:
#        - name: volume
#          emptyDir: {}
#      containers:
#        - name: nginx-1
#          image: nginx
#          volumeMounts:
#            - mountPath: /usr/share/nginx/html
#              name: volume
#      initContainers:
#        - name: debian-container
#          image: debian
#          command:
#            - /bin/bash
#          args: ["-c", "echo From Shared Data >  /root/volume3/index.html"]
#          volumeMounts:
#            - mountPath: /root/volume3
#              name: volume