global:
  evaluation_interval: 30s
  scrape_interval: 30s
  external_labels:
    prometheus: monitoring/k8s
  rule_files:
    - /etc/prometheus/rules/*.yml
  scrape_configs:
    - job_name: kubernetes-nodes
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node

    - job_name: prometheus
      honor_labels: false
      kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
              - monitoring
      scrape_interval: 30s
      relabel_configs:
        - action: keep
          source_labels:
            - __meta_kubernetes_service_label_prometheus
          regex: k8s
        - source_labels:
            - __meta_kubernetes_endpoint_address_target_kind
            - __meta_kubernetes_endpoint_address_target_name
          separator: ;
          regex: Pod;(.*)
          replacement: ${1}
          target_label: pod
        - source_labels:
            - __meta_kubernetes_namespace
          target_label: namespace
        - source_labels:
            - __meta_kubernetes_service_name
          target_label: service
        - source_labels:
            - __meta_kubernetes_pod_name
          target_label: pod
        - source_labels:
            - __meta_kubernetes_service_name
          target_label: job
          replacement: ${1}
        - target_label: endpoint
          replacement: web